//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentChain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartaments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartaments()
        {
            this.ApartmentPhotos = new HashSet<ApartmentPhotos>();
            this.Booking = new HashSet<Booking>();
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int ID { get; set; }
        public int AddressID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public double Price { get; set; }
        public Nullable<int> MaxAmountOfPeople { get; set; }
    
        public virtual ApartmentAddress ApartmentAddress { get; set; }
        public virtual ApartmentStatus ApartmentStatus { get; set; }
        public virtual ApartmentType ApartmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentPhotos> ApartmentPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
