//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentChain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID { get; set; }
        public System.DateTime DateOFPayment { get; set; }
        public int MethodID { get; set; }
        public int BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual MethodOfPay MethodOfPay { get; set; }
    }
}
