//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentChain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ApartmentID { get; set; }
        public string Review { get; set; }
        public int Rating { get; set; }
    
        public virtual Apartaments Apartaments { get; set; }
        public virtual Users Users { get; set; }
    }
}
